### Need of NumPy(Open source library)

By using Python, we can perform basic maths operations.
a,b=10,20
math.sqrt(4) like this
------but when we talk about DS(data science),ML,DL there we need stats operations,linear algebra,matrices,complex mathematical operations etc for those operation python doesn't have any such inbuilt library so we need third party lib NumPy----
1. creations of arrays/matrices
2. perform several operations on  arrays/matrices
3. perform integral calculas operations
4. solving differential equations
5. stats related operations
just because of extra libraries like numpy,pandas,sklearn,matplotlib, python is preferred language for data science.


# Array creation

There are 6 general mechanisms for creating arrays:

1. Conversion from other Python structures (i.e. lists and tuples)

2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3. Replicating, joining, or mutating existing arrays

4. Reading arrays from disk, either from standard or custom formats

5. Creating arrays from raw bytes through the use of strings or buffers

6. Use of special library functions (e.g., random)


------------------------1.using python structures------------------

Arrays
NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:

a list of numbers will create a 1D array,

a list of lists will create a 2D array,

further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])



1D arrays

methods: 1. np.arange(start,stop,step) # stop is excluded 2. np.linspace(start,stop,step)  # stop is included

2D arrays

The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define properties of special matrices represented as 2D arrays.

np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:
np.eye(3, 5)

numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements
np.diag([1, 2, 3])


methods: 

ndarrays

numpy.zeros will create an array filled with 0 values with the specified shape. The default dtype is float64:

np.zeros((2, 3))
array([[0., 0., 0.],
       [0., 0., 0.]])
np.zeros((2, 3, 2))
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])
        
numpy.ones will create an array filled with 1 values. It is identical to zeros in all other respects as such:


The random method of the result of default_rng will create an array filled with random values between 0 and 1. It is included with the numpy.random library. Below, two arrays are created with shapes (2,3) and (2,3,2), respectively. The seed is set to 42 so you can reproduce these pseudorandom numbers:


numpy.indices will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension:

np.indices((3,3))
array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],
       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])
        
vander(x, n) defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, x where the highest polynomial order is n-1. This array creation routine is helpful in generating linear least squares models, as such:

np.vander(np.linspace(0, 2, 5), 2)
array([[0. , 1. ],
      [0.5, 1. ],
      [1. , 1. ],
      [1.5, 1. ],
      [2. , 1. ]])
np.vander([1, 2, 3, 4], 2)
array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])
np.vander((1, 2, 3, 4), 4)
array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])
        
        
        
        
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
print(A,"\n",B,'\n',C,'\n',D)
        
        
3) Replicating, joining, or mutating existing arrays
Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array. Consider the following example:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)
a = [2 3 3 4 5 6] ; b = [2 3]

In [106]:
np.vander([10,20,30],4)


array([[ 1000,   100,    10,     1],
       [ 8000,   400,    20,     1],
       [27000,   900,    30,     1]])

In [92]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)


unsigned c: [4294967293 4294967293 4294967293] uint32
signed c: [-3 -3 -3] int64


### history of NumPy

NumPy: stands for numerical library
it is fundamental python library to perform complex numerical operations.
it is developed on top of numeric library in 2005.
numeric library developed by Gim Hugunin.
NumPy is developed by Travis Oliphant and multiple contributors.


### language of NumPy

It is wriiten in Python and C language( that's why performance wise it is very good(speed is high).
Because of high speed, NumPy is the best choice for ML algorithm than traditional python's in built data structures like LIST.

### features of Numpy

NumPy is superfast because it is developed in C language.
NumPy is backbone for data science libraries like Pandas,sk-learn etc.
Pandas internally use 'nd array' to store data,which is NumPy data structure.
scikit-learn also user internally 'nd array'.
Numpy has vectorization feature is there  which improve performance while iterating elements.


### nd array in Numpy

1 In NumPy we can hold data using array data structure .
2 The arrays created using NumPy, called nd arrays.
3 nd array --> N -dimentional array --> or NumPy array
4 This nd array is most commonly used in data science libraries like pandas,sk-learn etc.
5 Array: An indexed collection of homogeneous elements.
6 NumPy contains several functions to create nd arrays to perform several operations.


### NumPy's array VS List

Performance is very High of nd array over list.
but
nd array can only hold homogeneous elements but list can caontain heterogeneous elements also.

### Application area of NumPy

1. To perform linear algebra functions
2. To perform linear regression
3. To perform logistic regression
4. Deep neural networks
5. control systems
6. operational reseach
7. etc

Numpy is fundamental and mandatory library for data science, ML,DL.

### How to install NumPy

1. By using Anaconda distribution (Anaconda is python flavour for data science, ML etc.)
   Anaconda distribution has inbuilt numpy library and hence we are not required to install it
    
2. If python is already installed in our system, then we can install NumPy as follows:
    pip install numpy

In [1]:
import numpy as np
c=np.array([20,40,30])
d=np.array([2,4,3])

In [2]:
from datetime import datetime

In [3]:

def dot_product(a,b):
    result=0
    for m,n in zip(a,b):
        result+=m*n
    
    
a=[20,40,30]
b=[2,4,3]



In [4]:
before=datetime.now()
for i in range(10000):
    np.dot(c,d)
after=datetime.now()
print("time taken",after-before)

time taken 0:00:00.018941


### What is an Array

It is indexed collection of homogeneous elements.
It is the most commonly used concept in programming languages like C,C++,Java etc
by default we do not have arrays concept in python, instead we can use lists.
(but both list and array are not same)
but in python, we can create arrays in the following 2 ways.
1. By using array module.
2. By using NumPy module. (alway go with this because a lot library support)



In [5]:
import array 
a=array.array("i",[10,20,30])          # array means integer...2 times array because 1 is module name,second is function name

In [6]:
print(a)

array('i', [10, 20, 30])


### Differences between lists and arrays

1. list is inbuild data type but numpy array is not inbuilt. to use numpy arrays we need to install and import numpy library explicitly
2. List can hold heterogeneous elements but numpy array can only hold homogeneous elements.
3. on arrays we can performs vector operation(operations we apply on each and every elements) but we can not perform vector operation on lists.
4. Arrays consumes less memory when compare with lists.
5. arrays are superfast compare to list.
6. numpy arrays are more convenient while performing mathematical operations.

In [7]:
a=np.array([10,20,30,40,50,60])        # 3rd point
l=[20,30,40,50,60,60]
print(a/2)

import sys                    # 4th point
print("size of array",sys.getsizeof(a))
print("size of list",sys.getsizeof(l))

[ 5. 10. 15. 20. 25. 30.]
size of array 136
size of list 152


### Ways to create NumPy arrays

Numpy library contains several functions to create nd array based on our requirements.
1. array()
2. arange()
3. zeros()
4. ones()
5. linspace()
6. eye()
7. random()
8. full()
9. identity()
10. empty()


### Arrays attributes

1. ndim: to get dimension of the array
2. shape: to get shape of the array
3. size: to get size of array(number of elements)
4. dtype: to get data type of array elements
5. itemsize: the size of each element in bytes
6. 

In [8]:
a=np.array([10,40,40])
print(a.itemsize)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)

4
1
3
(3,)
int32


### NumPy data types

In python we have inbuilt data types like int,float,complex,boolstr, etc
But, NumPy has some extra data types in addition to these, we can represent data types by using a single character also.

1. i--->integer (int8,int16,int32,int64)--->by default int32
2. b--->boolean
3. u---> unsigned integer  (uint8,uint16,uint32,uint64)
4. f----> float   ---same as integer-->by default float64
5. c---> complex
6. s--->string
7. U---> unicode string
8. m----> datetime
etc

int8--

------------it reqyuires less memory than int16 dtype array---
value will be reprenseted by using 8 bits.
The range of values: -128 to 127

int16--

------------
value will be reprenseted by using 8 bits.
The range of values: -32768 to 32767


10.   how to create array with dtype
a=np.array([10,20,30],dtype='i')
print(a,type(a))

11. how to convert existing array type: a. by general we can use astype() function
  a=np.array([10,20,30],dtype='i')
print(a,type(a))
b=a.astype('float64')
print(b,type(b))

b. by using the corresponding data type function also, we can convert the type of array

a=np.array([10,20,30],dtype='i')
print(a,type(a))
b=np.float64(a)
print(b,type(b))




In [25]:
import sys
a=np.array([10,20,30])
b=np.array([10,20,30],dtype='float')
c=np.array([10,20,30],dtype='int64')
print(sys.getsizeof(a))
print(sys.getsizeof(b))
print(sys.getsizeof(c))

124
136
136


In [26]:
a=np.array([10,20,30],dtype='i')
print(a,type(a))
b=np.float64(a)
print(b,type(b))

[10 20 30] <class 'numpy.ndarray'>
[10. 20. 30.] <class 'numpy.ndarray'>


### Array Indexing concept

we can access one element at a time using index.
a[i]--->1 d array,  a[i][j]---> 2-d array where i-->row,j-->column, a[i][j][k]-->3d array where i--which 2d array 

by Using slice operator, we can access multiple objects but should be in order 
a[begin:end:step],a[begin:end:step,begin:end:step],a[begin:end:step,begin:end:step,begin:end:step]


If we want to access multiple elements which are not in order or if we want to access elements on some conditions then 
we can not use basic indexing and slicing operators. for this requirement, we should go for advanced indexing. 

Accessing multiple arbitrary elements:
    ---------------------
syntax:   a[x]
    x--> can be either nd array or sequence like list , which represents required indexes.
    
Accessing elements of 1D-array:
    -----------------
    
    a=np.array([10,20,30,69,78,60,80,100])
#### i want to access 10,69,80 from a, 1 -way is
#### create nd array with the required indexes and then by passing that array as argument we can access corresponding elements.
index=np.array([0,3,6])
a[index]

#### 2nd way: create list with required indexes and passing that list as argument we can access corresponding elements.
l=[0,3,7]
a[l]

#### we can not use above method for lists
#### we can access same elements multiple times
a[(0,2,5,0,2,5,6,6)]

#### tuple can not be used

Accessing elements of 2D-array:
    -----------------
    x[[row indexes],[column indexes]]
    
l=[[1,2,3,4],[3,4,5,8],[9,10,11,20],[12,13,14,30]]
m=np.array(l)
m[[0,1,2,3],[0,1,2,3]]   #### accessing diagonal elements


Accessing elements of 3D-array:
    -----------------
    syntax: array[[indexes of 2d array],[row index],[column index]]
    
    l=[[[1,2,3,4],[3,4,5,8],[9,1,20,22],[12,13,14,30]],[[11,22,33,44],[3,34,55,8],[29,5160,6161,620],[12,13,144,30]]]
m=np.array(l)
m.ndim
#### i want 4,5,5160,144
m[[0,0,1,1],[1,1,2,3],[1,2,1,2]]

## select array with condition

we can select array elements based on some condition also.

syntax: array[boolean_array]
    
    it selects all elements where boolean_array is True
    
    l=[-1,5,-10,6,7,-7,20]
a=np.array(l)
a
#### I want to select elements which are greater than 0.
#### create boolean_array
boolean_array=a<0
a[boolean_array]

### Slicing Vs advance indexing

In case of list, slice operator will create a separate copy of list.any changes in one copy ,would noty affect second one.

a1=[10,20,30]
a2=a1[:]
print(id(a1),id(a2))  # different ids it will through 3092717624000 3092717438528.


However, in numpy slicing, a new copy would not be created and just we are getting view of the existing nd array. If we perform any changes in original array, those changes will be reflected in slicing copy.

a1=np.array([10,20,30,40,60])
a2=a1[:4]
print(a1,a2) 
a1[0]=777
print(a1,a2) 

However in Advance indexing in NumPy, a new copy will be craeted,any changes in one copy ,would not affect second one

a1=np.array([10,20,30,40,60])
a2=a1[[0,2,3]]
print(a1,a2) 
a1[0]=777
print(a1,a2) 




# Arithmatic operations on nd array

+,-,*,/(it always return float),//(floor devision, it may return integer or float),%(remainder operator), ** exponential operator/power operator.

All above python's arithmetic mentioned operators are applicable on numpy array.

--------------Arithmetic operator on numpy array with scalar------------
scalar means: constant numeric value.
All arithmetic operator are applicable for numpy arrays with scalar.

eg: 1D array

a1=np.array([10,20,30,40,60])
print(a1**2)
print(a1/2)
print(a1*2)
print(a1//2)

applicable on all dimensions, 2D,3D.
NOTE*** : in python, divide by zero not possible. If we are trying to perform then we will get zeroDivionError.

In numpy, 0/0-->nan ans 10/0-->inf (infinity) you will not get devidebyzero error.anything/np.inf-->0

a1=np.array([0,20,30,40,60])
print(a1**2)
print(a1/2)
print(a1*2)
print(a1/0)
print(a1/np.inf)

--------------Arithmetic operator on numpy array with Array( Arrays with arrays)------------
here: dimension, shape, size should be same of both the numpy arrays.

a1=np.array([20,20,30,40,60,20])
b1=np.array([10,100,30,470,960])
print(a1+b1)
print(b1/a1)


---------broadcasting for different shapes---------
ValueError: operands could not be broadcast together with shapes (5,) (6,) 

####note: for every arithmetic function, numpy library defines equivalent functions. we can use these functions also.
1. a+b --->  np.add(a,b)
2. a-b --->  np.subtract(a,b)
3. a*b --->  np.multiply(a,b)
4. a/b --->  np.divide(a,b)
5. a//b --->  np.floor_divide(a,b)
6. a%b --->  np.mod(a,b)
7. a**b --->  np.power(a,b)




# Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

1. they are equal, or

2. one of them is 1

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes

When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.

a1=np.array([[20,20,30,40,20],[10,100,30,470,960]])
b1=np.array([10,100,30,470,960,70])    # trail mismatch

print(np.add(a1,b1))
print(a1)

example:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a.shape,b.shape)
print(a[:,np.newaxis]+b)



Here the newaxis index operator inserts a new axis into a, making it a two-dimensional 4x1 array. Combining the 4x1 array with b, which has shape (3,), yields a 4x3 array.

In [89]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a.shape,b.shape)
print(a[:,np.newaxis]+b)

(4,) (3,)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
